"""
Proactive Messages API.

- GET  /api/proactive/pending  — undelivered proactive messages for a user×character
- POST /api/proactive/ack      — mark messages delivered so they are not re-served

Messages are persisted in the ``proactive_messages`` table by the SS06 Inner
Loop worker, so this survives process restarts.
"""

from __future__ import annotations

from typing import List, Optional
from uuid import UUID

import structlog
from fastapi import APIRouter, Depends, HTTPException, Query, Request
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession

from heart.api.rate_limit import limiter
from heart.api.wiring import get_db
from heart.core.auth import TokenData, get_current_user
from heart.ss06_inner_state import proactive_repo

logger = structlog.get_logger(__name__)

router = APIRouter(prefix="/api/proactive", tags=["proactive"])


class AckRequest(BaseModel):
    """Body for POST /api/proactive/ack."""

    message_ids: List[UUID]


@router.get("/pending")
@limiter.limit("60/minute")
async def get_pending_messages(
    request: Request,
    user_id: UUID = Query(..., description="User UUID"),
    character_id: Optional[str] = Query(None, description="Character ID filter"),
    current_user: TokenData = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Get undelivered proactive messages for a user.

    Returns proactive messages generated by the Inner Loop worker that have not
    yet been acknowledged (delivered). Query params:
        user_id: User UUID (required)
        character_id: Optional character filter
    """
    if str(current_user.user_id) != str(user_id):
        raise HTTPException(403, "Cannot read another user's proactive messages")

    messages = await proactive_repo.fetch_pending(
        db,
        user_id=user_id,
        character_id=character_id,
    )

    return {
        "user_id": str(user_id),
        "character_id": character_id,
        "count": len(messages),
        "messages": [
            {
                "id": str(m.id),
                "character_id": m.character_id,
                "content": m.content,
                "trigger_type": m.trigger_type,
                "created_at": m.created_at.isoformat(),
            }
            for m in messages
        ],
    }


@router.post("/ack")
@limiter.limit("60/minute")
async def ack_messages(
    request: Request,
    body: AckRequest,
    user_id: UUID = Query(..., description="User UUID"),
    current_user: TokenData = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Mark proactive messages as delivered so they are not returned again."""
    if str(current_user.user_id) != str(user_id):
        raise HTTPException(403, "Cannot acknowledge another user's proactive messages")

    updated = await proactive_repo.mark_delivered(
        db,
        user_id=user_id,
        message_ids=body.message_ids,
    )

    return {"acknowledged": updated}
