"""
Proactive Messages API — GET /api/proactive/pending

Returns pending proactive messages for a user×character pair.
Used by CLI to poll for proactive messages from the Inner Loop.
"""

from __future__ import annotations

from typing import Optional
from uuid import UUID

import structlog
from fastapi import APIRouter, Query

from heart.ss06_inner_state.inner_loop_worker import get_pending_proactive_messages

logger = structlog.get_logger(__name__)

router = APIRouter(prefix="/api/proactive", tags=["proactive"])


@router.get("/pending")
async def get_pending_messages(
    user_id: UUID = Query(..., description="User UUID"),
    character_id: Optional[str] = Query(None, description="Character ID filter"),
):
    """Get pending proactive messages for a user.

    Returns proactive messages generated by the Inner Loop worker
    that haven't been delivered yet.

    Query params:
        user_id: User UUID (required)
        character_id: Optional character filter
    """
    messages = get_pending_proactive_messages(
        user_id=user_id,
        character_id=character_id,
    )

    return {
        "user_id": str(user_id),
        "character_id": character_id,
        "count": len(messages),
        "messages": [
            {
                "id": str(m.id) if hasattr(m, "id") else None,
                "character_id": m.character_id,
                "content": m.content,
                "trigger_type": m.trigger_type,
                "created_at": m.created_at.isoformat(),
            }
            for m in messages
        ],
    }
