import type { CSSProperties, ReactNode } from 'react'

function Wrap({ kind, accent, children }: { kind: string; accent: string; children: ReactNode }) {
  return (
    <section className={`b11-chat-card ${kind}`} style={{ '--a': accent } as CSSProperties}>
      <style>{`
        .b11-chat-card{margin:9px 2px 5px;padding:15px;color:var(--ink);background:var(--bg);border:1px solid var(--line);font-family:-apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif;letter-spacing:0;overflow:visible;flex:0 0 auto;height:auto;min-height:max-content}.b11-chat-card *{box-sizing:border-box;letter-spacing:0}.b11-chat-card h3{font:600 17px/1.4 "Songti SC","STSong",serif}.b11-chat-card p{font-size:11px;line-height:1.7}.b11-chat-card small{font:8px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted)}.b11-chat-card b{font-weight:650}.b11-chat-card{--bg:rgba(255,255,255,.88);--ink:#28282b;--muted:#777780;--line:rgba(38,38,42,.14)}[data-theme="dark"] .b11-chat-card{--bg:rgba(25,26,30,.9);--ink:#eeeef0;--muted:#999aa3;--line:rgba(255,255,255,.12)}
        .b11-mirror{border:3px double #aaa69e;background-image:linear-gradient(115deg,transparent 38%,rgba(180,190,194,.14) 39%,transparent 42%)}.b11-mirror .measure{border-bottom:1px dashed #8b8983;padding-bottom:7px}.b11-mirror h3{margin:14px 0 8px}.b11-mirror .note{margin-top:12px;background:#fff1a8;color:#4b4433;padding:10px;transform:rotate(-1deg);font-family:"Kaiti SC",serif}
        .b11-scroll{background:linear-gradient(90deg,#3a191a 0 50%,#0d2944 50%);color:#eee7d8;border-color:#8d3135}.b11-scroll header{display:flex;justify-content:space-between}.b11-scroll .seal{border:2px solid #c13c43;border-radius:50%;padding:8px;color:#e1676b;transform:rotate(-8deg)}.b11-scroll h3{margin:13px 0}.b11-scroll .power{height:5px;background:#1b1f26}.b11-scroll .power i{display:block;width:43%;height:100%;background:linear-gradient(90deg,#bd3439,#8eb6df)}
        .b11-cctv{background:#0e0e0f;color:#ddd;border-color:#393939}.b11-cctv header{display:flex;justify-content:space-between;color:#888}.b11-cctv header b{color:#d9484c}.b11-cctv .grid{display:grid;grid-template-columns:1.2fr .8fr;gap:5px;margin:10px 0}.b11-cctv .cam{height:75px;border:1px solid #333;background:repeating-linear-gradient(0deg,#171717 0 3px,#202020 4px);padding:7px}.b11-cctv .cam:first-child{grid-row:span 2;height:auto}.b11-cctv blockquote{border-left:2px solid #b9383e;padding:8px 10px;color:#e28c90;font-size:11px}
        .b11-chip{background:#0c2b21;color:#eadfc9;border-color:#9d7b45;border-radius:45%/16%;text-align:center}.b11-chip .stack{display:flex;justify-content:center;margin:12px 0}.b11-chip .stack i{width:38px;height:38px;border:3px dashed #d5b16d;border-radius:50%;background:#702c30;display:grid;place-items:center;margin-left:-6px;font-style:normal}.b11-chip .rule{border-top:1px solid #8a714a;padding-top:9px;color:#cdb888}
        .b11-notes{background:repeating-linear-gradient(0deg,#f6f1df 0 24px,#bdd1df 25px);color:#2d3a45;border-left:2px solid #df9f9f}.b11-notes h3{margin:8px 0 11px}.b11-notes .equation{font-family:"Kaiti SC",serif}.b11-notes .red{color:#a55056;margin-top:9px;font-family:"Kaiti SC",serif}.b11-notes .stud{float:right;width:8px;height:8px;border-radius:50%;background:#bbbfc4;box-shadow:0 0 6px #7998aa}
        .b11-living{background:#191919;color:#e7e1d8;border-color:#4d4235}.b11-living .room{height:86px;margin-bottom:12px;background:linear-gradient(#222 0 62%,#111 62%);position:relative}.b11-living .sofa{position:absolute;left:17px;bottom:17px;width:104px;height:29px;background:#333}.b11-living .bowl{position:absolute;right:25px;bottom:22px;color:#d7b078}.b11-living h3{color:#d5ba90}.b11-living p{margin-top:7px;color:#b8afa4}
        .b11-tray{background:linear-gradient(145deg,#d2d9da,#f4f7f7);color:#252b2d;border:2px solid #9ea7aa;border-radius:12px}.b11-tray .tools{height:62px;position:relative}.b11-tray .needle{position:absolute;width:115px;height:4px;background:#7e898c;top:24px;left:17px;transform:rotate(10deg)}.b11-tray .cotton{position:absolute;width:48px;height:41px;background:#fff;right:18px;top:8px;box-shadow:7px 6px 0 #e9eeee}.b11-tray .follow{margin-top:10px;border-top:1px solid #9da6a8;padding-top:9px;color:#687579}
        .b11-vip{background:#071e17;color:#eadfcb;border-color:#936d3d}.b11-vip .drawing{background:#e4d4b2;color:#3d3429;margin:11px 0;padding:11px;transform:rotate(-1deg);font-family:"Kaiti SC",serif}.b11-vip .refuse{display:flex;justify-content:space-between;border-top:1px solid #735a3d;padding-top:9px}.b11-vip .refuse b{color:#d0a968}
        .b11-phone{background:#171920;color:#e9e9ed;border-color:#343741;border-radius:19px}.b11-phone header{text-align:center;border-bottom:1px solid #32343d;padding-bottom:9px}.b11-phone .bubble{width:max-content;max-width:85%;background:#2b2e37;padding:7px 9px;border-radius:3px 12px 12px;margin:7px 0;font-size:10px}.b11-phone .pay{margin:7px 0 0 auto;background:#d58437;padding:8px 10px;width:72%;border-radius:7px}.b11-phone .pay b{display:block;font-size:14px}
        .b11-file{background:#cbbda4;color:#29241e;border-color:#6b5e4c;position:relative}.b11-file .stamp{position:absolute;right:13px;top:12px;color:#992f30;border:3px double #992f30;padding:7px;transform:rotate(-10deg)}.b11-file h3{margin:20px 0 8px}.b11-file .medical{background:#e2ddd2;margin-top:11px;padding:9px;border-left:4px solid #822f30}.b11-file .pocket{margin-top:8px;background:#292a2d;color:#ddd;padding:9px}
      `}</style>
      {children}
    </section>
  )
}

export function QinJingzhouPremiseCard() { return <Wrap kind="b11-mirror" accent="#8c8981"><small className="measure">FITTING ROOM / V5.0</small><h3>前任的婚服，指定由你设计</h3><p>五年前你因现实离开穷困的他。如今他带着商业联姻对象回来，只问你有没有话想说。</p><div className="note">袖口改过三次 / 她说的<br />旧版客户栏：你的名字</div></Wrap> }
export function YeJinghengPremiseCard() { return <Wrap kind="b11-scroll" accent="#a63036"><header><small>北镇抚司 · 亡字柒拾一</small><b className="seal">未结</b></header><h3>烛火这一边是哥哥，月光那一边是鬼</h3><p>每查清一条丞相旧案，弟弟便失去一段关于锦衣卫兄长的记忆。</p><div className="power"><i /></div></Wrap> }
export function LuoZhiyePremiseCard() { return <Wrap kind="b11-cctv" accent="#b9393f"><header><small>VILLA SECURITY</small><b>● REC</b></header><div className="grid"><div className="cam">客厅 / 23:41</div><div className="cam">工作 / 未归</div><div className="cam">卧室 / 呼吸正常</div></div><blockquote>解约文件已撕毁。你以为自己来训斥偶像，他却早已收购整家公司。</blockquote></Wrap> }
export function HanJingmoPremiseCard() { return <Wrap kind="b11-chip" accent="#c6a15e"><small>PRIVATE TABLE / FAMILY RULE 01</small><div className="stack"><i>你</i><i>的</i><i>名</i><i>字</i></div><h3>新女儿进门，你的房间仍亮着</h3><p className="rule">他嘴上让你保持距离，拒绝之后送来的礼物却一次比一次贵。</p></Wrap> }
export function XuYanzhiPremiseCard() { return <Wrap kind="b11-notes" accent="#68879c"><small>高三（二）班 · 第 4 节数学课</small><i className="stud" /><h3>公式里夹着一行不该出现的字</h3><p className="equation">lim x→∞ · 笔尖停了 7 秒<br />左耳银钉被发丝重新遮住</p><p className="red">她今天又笑了。</p></Wrap> }
export function ShangYanliPremiseCard() { return <Wrap kind="b11-living" accent="#c29f6d"><div className="room"><i className="sofa" /><i className="bowl">热粥 ⌇</i></div><small>HOME / 01:47 / WAITING 04:12:33</small><h3>客厅没开灯，他一个人等到你回家</h3><p>对外活阎王，对内……老婆说什么就是什么。</p></Wrap> }
export function ShenLiPremiseCard() { return <Wrap kind="b11-tray" accent="#68767a"><small>STERILE TRAY / FIRST VISIT</small><div className="tools"><i className="needle" /><i className="cotton" /></div><h3>“有对象吗？”听起来只是术前询问</h3><p>他拒绝让你一次打完三个孔，却把你没选的那枚耳钉买下藏好。</p><p className="follow">下次复查：七天后 · 联系方式已添加</p></Wrap> }
export function FuYichenPremiseCard() { return <Wrap kind="b11-vip" accent="#bd8b49"><small>VIP ROOM / PRIVATE LEDGER</small><h3>每一次“唔得”，后面都跟着更贵的礼物</h3><div className="drawing">五岁的全家福<br />“爸爸”头顶画着皇冠</div><div className="refuse"><span>今晚再次拒绝</span><b>补偿：未登记</b></div></Wrap> }
export function XuChangyePremiseCard() { return <Wrap kind="b11-phone" accent="#65ce98"><header><h3>许常夜</h3><small>● 在线 · 正在输入</small></header><div className="bubble">宝宝，你理理我嘛……</div><div className="bubble">是不是我太烦了？</div><div className="pay"><b>¥ 52,000.00</b><small>别不理我</small></div></Wrap> }
export function SuChenPremiseCard() { return <Wrap kind="b11-file" accent="#8c3031"><i className="stamp">已故</i><small>CONFIDENTIAL / 寒鸦</small><h3>死了两年的哥哥，第一脚把你踢开</h3><p>手下正在看。他只能先让你恨他，才能让你活着离开巷口。</p><div className="medical">病历：重度贫血 · 鞋印覆盖</div><div className="pocket">内袋：半张合照 / 被碾皱的病历卡</div></Wrap> }
