"""
Unit tests for LLM-generated proactive messages (TEST_BUGS FR #1).

Proactive content is generated by the cheap LLM personalized to recent
context/facts, and MUST fall back to the built-in templates on any failure
or when the feature flag is off.
"""

from __future__ import annotations

from unittest.mock import AsyncMock, MagicMock, patch
from uuid import uuid4

import pytest

from heart.core.config import settings
from heart.ss01_soul.character_content import get_proactive_templates
from heart.ss06_inner_state.service import InnerStateService


def _mock_router(content: str) -> MagicMock:
    router = MagicMock()
    router.call_cheap = AsyncMock(return_value=content)
    return router


def test_build_prompt_includes_persona_and_facts():
    prompt = InnerStateService._build_proactive_prompt(
        character_id="rin",
        trigger_type="event_driven",
        relationship_stage="FRIEND",
        intimacy=0.5,
        days_since_last_interaction=2.0,
        recent_context="- 聊了面试",
        user_facts="- 用户 worries_about 自我介绍",
    )
    assert "rin" in prompt
    assert "神无月凛" in prompt  # persona hint injected
    assert "自我介绍" in prompt  # facts injected
    assert "面试" in prompt


@pytest.mark.asyncio
async def test_generate_returns_trimmed_content():
    svc = InnerStateService()
    router = _mock_router('  "……突然想你了。"  ')
    with patch("heart.infra.llm_providers.get_model_router", AsyncMock(return_value=router)):
        content = await svc._generate_proactive_content(
            character_id="rin",
            trigger_type="scheduled",
            relationship_stage="FRIEND",
            intimacy=0.4,
            days_since_last_interaction=1.0,
            recent_context="",
            user_facts="",
        )
    assert content == "……突然想你了。"  # quotes + whitespace stripped
    router.call_cheap.assert_awaited_once()


@pytest.mark.asyncio
async def test_generate_returns_none_on_empty():
    svc = InnerStateService()
    router = _mock_router("   ")
    with patch("heart.infra.llm_providers.get_model_router", AsyncMock(return_value=router)):
        content = await svc._generate_proactive_content(
            character_id="rin",
            trigger_type="scheduled",
            relationship_stage="FRIEND",
            intimacy=0.4,
            days_since_last_interaction=1.0,
            recent_context="",
            user_facts="",
        )
    assert content is None


@pytest.mark.asyncio
async def test_resolve_falls_back_to_template_on_llm_error():
    svc = InnerStateService()
    router = MagicMock()
    router.call_cheap = AsyncMock(side_effect=RuntimeError("boom"))
    with (
        patch.object(settings, "proactive_llm_enabled", True),
        patch("heart.infra.llm_providers.get_model_router", AsyncMock(return_value=router)),
    ):
        content = await svc._resolve_proactive_content(
            character_id="rin",
            trigger_type="scheduled",
            relationship_stage="FRIEND",
            intimacy=0.4,
            days_since_last_interaction=1.0,
            recent_context="",
            user_facts="",
        )
    assert content in get_proactive_templates("rin")


@pytest.mark.asyncio
async def test_resolve_uses_template_when_disabled():
    svc = InnerStateService()
    router = _mock_router("这条不该被用到")
    with (
        patch.object(settings, "proactive_llm_enabled", False),
        patch("heart.infra.llm_providers.get_model_router", AsyncMock(return_value=router)),
    ):
        content = await svc._resolve_proactive_content(
            character_id="rin",
            trigger_type="scheduled",
            relationship_stage="FRIEND",
            intimacy=0.4,
            days_since_last_interaction=1.0,
            recent_context="",
            user_facts="",
        )
    assert content in get_proactive_templates("rin")
    router.call_cheap.assert_not_awaited()


@pytest.mark.asyncio
async def test_tick_emits_llm_content_when_sending():
    """When a proactive fires, the message content comes from the LLM."""
    svc = InnerStateService()
    router = _mock_router("今天的风让我想起你。")
    with (
        patch.object(settings, "proactive_llm_enabled", True),
        patch("heart.infra.llm_providers.get_model_router", AsyncMock(return_value=router)),
        # Force the probabilistic send gate to fire.
        patch("heart.ss06_inner_state.service.random.random", return_value=0.0),
        patch("heart.ss06_inner_state.service.random.uniform", return_value=0.0),
    ):
        msg = await svc.tick(
            uuid4(),
            "rin",
            relationship_stage="FRIEND",
            intimacy=0.8,
            days_since_last_interaction=2.0,
        )
    assert msg is not None
    assert msg.content == "今天的风让我想起你。"
