"""
Proactive Scheduler — SS06 Inner State & Behavior §3.9, §10.1, §10.7

Redis ZSET-backed scheduling for proactive messages generated by the Initiative
Decider → Proactive Message Generator pipeline.  Receives a PendingInitiative,
inserts it into a Redis sorted set ordered by scheduled_at, and provides a
background worker (ProactiveSender) that polls due items and dispatches them
to the notification/conversation layer.

Key invariants:
  - INV-I-2: scheduled_at ∉ quiet_hours ∧ interval ≥ MIN_PROACTIVE_GAP
  - I-4: Proactive must obey quiet hours + frequency cap
  - Idempotency: never double-fire the same initiative

Architecture:
  Redis ZSET  proactive:queue:{user_id}:{character_id}   score = scheduled_at
  Redis SET   proactive:sent:{user_id}:{character_id}    idempotency guard
  Redis STRING proactive:lock:{initiative_id}            dispatch mutex

Spec:   runtime_specs/06_inner_state_behavior_runtime.md §3.9, §5.3, §10.1, §10.7
Author: 心屿团队
"""

from __future__ import annotations

import json
import random
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Any, Callable, Dict, List, Optional, Protocol
from uuid import UUID, uuid4

# ------------------------------------------------------------------
# Protocols for dependency injection (testable without real Redis)
# ------------------------------------------------------------------


class RedisClient(Protocol):
    """Minimal Redis client interface consumed by the scheduler."""

    def zadd(self, name: str, mapping: Dict[str, float], nx: bool = False) -> int: ...
    def zrangebyscore(
        self,
        name: str,
        min: float,
        max: float,
        withscores: bool = False,
        start: int | None = None,
        num: int | None = None,
    ) -> list: ...
    def zrem(self, name: str, *values: str) -> int: ...
    def zcard(self, name: str) -> int: ...
    def sadd(self, name: str, *values: str) -> int: ...
    def sismember(self, name: str, value: str) -> bool: ...
    def srem(self, name: str, *values: str) -> int: ...
    def set(self, name: str, value: str, ex: int | None = None) -> bool: ...
    def get(self, name: str) -> bytes | None: ...
    def delete(self, *names: str) -> int: ...
    def scan_iter(self, match: str | None = None, count: int | None = None) -> list: ...
    def keys(self, pattern: str) -> list: ...


# ------------------------------------------------------------------
# Data structures
# ------------------------------------------------------------------


@dataclass
class PendingInitiative:
    """A proactive message queued for scheduled delivery.

    Per spec §5.3 PendingInitiative:
      initiative_id, initiative_type, scheduled_at, scheduled_with_jitter,
      context, generated_message, status, created_at, sent_at
    """

    initiative_id: str  # UUID string

    # Identity
    user_id: UUID
    character_id: str

    # Timing
    scheduled_at: datetime  # base time (before jitter)
    scheduled_with_jitter: datetime  # actual target delivery time

    # Content
    initiative_type: str  # TriggerType value
    generated_message: str

    # State
    status: str = "ready"  # ready | sent | cancelled
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    sent_at: Optional[datetime] = None

    # Type-specific context (anniversary, concern, etc.)
    context: Dict[str, Any] = field(default_factory=dict)

    # Dispatch attempts
    attempts: int = 0
    last_attempt_at: Optional[datetime] = None

    # ─── serialization ───

    def to_json(self) -> str:
        """Serialize to JSON for ZSET member storage."""
        return json.dumps(
            {
                "initiative_id": self.initiative_id,
                "user_id": str(self.user_id),
                "character_id": self.character_id,
                "scheduled_at": self.scheduled_at.isoformat(),
                "scheduled_with_jitter": self.scheduled_with_jitter.isoformat(),
                "initiative_type": self.initiative_type,
                "generated_message": self.generated_message,
                "status": self.status,
                "created_at": self.created_at.isoformat(),
                "sent_at": self.sent_at.isoformat() if self.sent_at else None,
                "context": self.context,
                "attempts": self.attempts,
            },
            ensure_ascii=False,
        )

    @classmethod
    def from_json(cls, raw: str) -> "PendingInitiative":
        """Deserialize from JSON."""
        d = json.loads(raw)
        return cls(
            initiative_id=d["initiative_id"],
            user_id=UUID(d["user_id"]),
            character_id=d["character_id"],
            scheduled_at=datetime.fromisoformat(d["scheduled_at"]),
            scheduled_with_jitter=datetime.fromisoformat(d["scheduled_with_jitter"]),
            initiative_type=d.get("initiative_type", ""),
            generated_message=d.get("generated_message", ""),
            status=d.get("status", "ready"),
            created_at=datetime.fromisoformat(d["created_at"])
            if d.get("created_at")
            else datetime.now(timezone.utc),
            sent_at=datetime.fromisoformat(d["sent_at"]) if d.get("sent_at") else None,
            context=d.get("context", {}),
            attempts=d.get("attempts", 0),
        )


@dataclass
class ScheduleResult:
    """Result of a schedule operation."""

    initiative_id: str
    success: bool
    error: Optional[str] = None
    position: int = 0  # queue position after insertion (1-based)


@dataclass
class DispatchResult:
    """Result of attempting to dispatch a due initiative."""

    initiative_id: str
    dispatched: bool
    reason: str = ""
    message: Optional[str] = None


# ------------------------------------------------------------------
# Constants
# ------------------------------------------------------------------

# Default jitter window in seconds (± 5 minutes per spec §7.5)
DEFAULT_JITTER_SECONDS = 5 * 60

# Lock TTL (seconds) for dispatch mutex — long enough to send
DISPATCH_LOCK_TTL = 30

# Redis key templates
QUEUE_KEY = "proactive:queue:{user_id}:{character_id}"
SENT_KEY = "proactive:sent:{user_id}:{character_id}"
LOCK_KEY = "proactive:lock:{initiative_id}"


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------


def _to_timestamp(dt: datetime) -> float:
    """Convert a timezone-aware datetime to a Unix timestamp float."""
    return dt.timestamp()


def _from_timestamp(ts: float) -> datetime:
    """Convert a Unix timestamp back to a UTC datetime."""
    return datetime.fromtimestamp(ts, tz=timezone.utc)


def _add_jitter(
    base: datetime,
    jitter_seconds: int = DEFAULT_JITTER_SECONDS,
    rng: random.Random | None = None,
) -> datetime:
    """Add ±jitter_seconds to the scheduled time (avoids mechanical feel).

    Per spec §7.5: "Schedule with jitter ±5min"
    """
    rng = rng or random.Random()
    offset = rng.randint(-jitter_seconds, jitter_seconds)
    return base + timedelta(seconds=offset)


# ------------------------------------------------------------------
# ProactiveScheduler — Redis ZSET queue
# ------------------------------------------------------------------


class ProactiveScheduler:
    """Redis ZSET-backed proactive initiative scheduler.

    Usage::

        scheduler = ProactiveScheduler(redis_client)
        scheduler.schedule(initiative)
        # ... later in background worker ...
        due = scheduler.poll_due(user_id, character_id)
        for item in due:
            scheduler.mark_sent(item)

    Idempotency guarantee:
      - Before dispatching, check sent-set.  If already present → skip.
      - Use Redis SETNX-style lock during dispatch to prevent concurrent double-fire.
    """

    def __init__(self, redis: RedisClient) -> None:
        self._redis = redis

    # ─── Key builders ───

    @staticmethod
    def _queue_key(user_id: UUID, character_id: str) -> str:
        return QUEUE_KEY.format(user_id=str(user_id), character_id=character_id)

    @staticmethod
    def _sent_key(user_id: UUID, character_id: str) -> str:
        return SENT_KEY.format(user_id=str(user_id), character_id=character_id)

    @staticmethod
    def _lock_key(initiative_id: str) -> str:
        return LOCK_KEY.format(initiative_id=initiative_id)

    # ─── Schedule ───

    def schedule(self, initiative: PendingInitiative, apply_jitter: bool = False) -> ScheduleResult:
        """Insert a PendingInitiative into the ZSET queue.

        If *apply_jitter* is True, applies ±5 min jitter if scheduled_with_jitter
        equals scheduled_at (i.e. hasn't already been jittered).  Usually the
        caller (InnerLoopScheduler) sets scheduled_with_jitter before calling,
        so this flag is False by default.
        """
        if apply_jitter and initiative.scheduled_at == initiative.scheduled_with_jitter:
            initiative.scheduled_with_jitter = _add_jitter(initiative.scheduled_at)

        key = self._queue_key(initiative.user_id, initiative.character_id)
        score = _to_timestamp(initiative.scheduled_with_jitter)

        # Store full initiative as JSON in the ZSET member
        member = initiative.to_json()

        try:
            self._redis.zadd(key, {member: score})
        except Exception as exc:
            return ScheduleResult(
                initiative_id=initiative.initiative_id,
                success=False,
                error=str(exc),
            )

        count = self._redis.zcard(key)
        position = max(count, 1)

        return ScheduleResult(
            initiative_id=initiative.initiative_id,
            success=True,
            position=position,
        )

    # ─── Poll due ───

    def poll_due(
        self,
        user_id: UUID,
        character_id: str,
        now: datetime | None = None,
        limit: int = 10,
    ) -> List[PendingInitiative]:
        """Return initiatives whose scheduled_with_jitter ≤ *now*.

        Returns up to *limit* items, oldest first.
        """
        now = now or datetime.now(timezone.utc)
        now_ts = _to_timestamp(now)
        key = self._queue_key(user_id, character_id)

        raw = self._redis.zrangebyscore(key, 0, now_ts, withscores=False, num=limit)

        results: List[PendingInitiative] = []
        for member in raw:
            try:
                init = PendingInitiative.from_json(member)
                results.append(init)
            except (json.JSONDecodeError, KeyError, ValueError):
                continue
        return results

    def poll_all_due(
        self,
        now: datetime | None = None,
        limit: int = 100,
    ) -> List[PendingInitiative]:
        """Scan ALL user/character queue keys and return due initiatives.

        Uses Redis SCAN to discover queue keys, then ZRANGEBYSCORE each.
        Suitable for the background worker.
        """
        now = now or datetime.now(timezone.utc)
        now_ts = _to_timestamp(now)

        results: List[PendingInitiative] = []

        # Discover all queue keys
        pattern = "proactive:queue:*"
        try:
            keys = list(self._redis.scan_iter(match=pattern))
        except AttributeError:
            # Fallback to KEYS (fakeredis / older redis-py compatibility)
            keys = list(self._redis.keys(pattern))

        for key in keys:
            raw = self._redis.zrangebyscore(key, 0, now_ts, withscores=False, num=limit)
            for member in raw:
                try:
                    init = PendingInitiative.from_json(member)
                    results.append(init)
                except (json.JSONDecodeError, KeyError, ValueError):
                    continue
                if len(results) >= limit:
                    break
            if len(results) >= limit:
                break

        # Sort by scheduled time, oldest first
        results.sort(key=lambda i: i.scheduled_with_jitter)
        return results[:limit]

    # ─── Idempotency ───

    def is_already_sent(self, initiative_id: str, user_id: UUID, character_id: str) -> bool:
        """Check if an initiative has already been dispatched."""
        sent_key = self._sent_key(user_id, character_id)
        return self._redis.sismember(sent_key, initiative_id)

    def mark_sent(self, initiative: PendingInitiative) -> bool:
        """Mark an initiative as sent (idempotency guard).

        Adds to sent-set and removes from the queue ZSET.  Returns True if
        this is a new marking, False if it was already in the sent set.
        """
        sent_key = self._sent_key(initiative.user_id, initiative.character_id)
        added = self._redis.sadd(sent_key, initiative.initiative_id)

        # Remove from queue ZSET by member payload
        queue_key = self._queue_key(initiative.user_id, initiative.character_id)
        member = initiative.to_json()
        self._redis.zrem(queue_key, member)

        return added > 0

    # ─── Cancel ───

    def cancel(
        self,
        initiative_id: str,
        user_id: UUID,
        character_id: str,
    ) -> int:
        """Cancel a single pending initiative by its id.

        Returns the number of items removed (0 or 1).
        """
        queue_key = self._queue_key(user_id, character_id)
        removed = 0
        members = self._redis.zrangebyscore(queue_key, 0, float("inf"), withscores=False)
        for member in members:
            try:
                init = PendingInitiative.from_json(member)
                if init.initiative_id == initiative_id:
                    self._redis.zrem(queue_key, member)
                    removed += 1
                    break
            except (json.JSONDecodeError, KeyError, ValueError):
                continue
        return removed

    def cancel_all(self, user_id: UUID, character_id: str) -> int:
        """Cancel all pending initiatives for a user/character pair.

        Returns the count of cancelled items.
        """
        queue_key = self._queue_key(user_id, character_id)
        count = self._redis.zcard(queue_key)
        if count > 0:
            self._redis.delete(queue_key)
        return count

    # ─── Query ───

    def get_pending(self, user_id: UUID, character_id: str) -> Optional[PendingInitiative]:
        """Return the next pending initiative (earliest scheduled), or None."""
        key = self._queue_key(user_id, character_id)
        raw = self._redis.zrangebyscore(key, 0, float("inf"), withscores=False, num=1)
        if raw:
            try:
                return PendingInitiative.from_json(raw[0])
            except (json.JSONDecodeError, KeyError, ValueError):
                return None
        return None

    def count_pending(self, user_id: UUID, character_id: str) -> int:
        """Count of pending initiatives in the queue."""
        return self._redis.zcard(self._queue_key(user_id, character_id))

    # ─── Dispatch lock (worker concurrency) ───

    def acquire_dispatch_lock(self, initiative_id: str) -> bool:
        """Try to acquire a dispatch mutex for this initiative.

        Uses Redis SET with NX + EX.  Returns True if lock acquired.
        """
        lock_key = self._lock_key(initiative_id)
        result = self._redis.set(lock_key, "1", ex=DISPATCH_LOCK_TTL)
        return bool(result)

    def release_dispatch_lock(self, initiative_id: str) -> None:
        """Release the dispatch lock."""
        self._redis.delete(self._lock_key(initiative_id))


# ------------------------------------------------------------------
# ProactiveSender — background worker (§10.7)
# ------------------------------------------------------------------


class ProactiveSender:
    """Background worker that polls the ZSET and dispatches due proactive messages.

    Per spec §10.7:  Poll every 10s, for each due item:
      1. Last-minute eligibility check
      2. Send via Push Notification
      3. Save as conversation message
      4. Mark sent
      5. Emit event

    The actual I/O (push notification, conversation save) is injected via a
    dispatch callback so the core logic remains testable.
    """

    def __init__(
        self,
        scheduler: ProactiveScheduler,
        on_dispatch: Callable[[PendingInitiative], DispatchResult] | None = None,
    ) -> None:
        self._scheduler = scheduler
        self._on_dispatch = on_dispatch or self._default_dispatch

    # ─── Public API ───

    def poll_and_dispatch(
        self,
        now: datetime | None = None,
        max_batch: int = 50,
    ) -> List[DispatchResult]:
        """Single poll-and-dispatch cycle.

        Returns results for each attempted item.
        """
        now = now or datetime.now(timezone.utc)

        due = self._scheduler.poll_all_due(now=now, limit=max_batch)
        results: List[DispatchResult] = []

        for init in due:
            result = self._dispatch_one(init)
            results.append(result)

        return results

    # ─── Internal ───

    def _dispatch_one(self, init: PendingInitiative) -> DispatchResult:
        """Attempt to dispatch a single due initiative with idempotency guard."""

        # --- Guard 1: already sent? ---
        if self._scheduler.is_already_sent(init.initiative_id, init.user_id, init.character_id):
            return DispatchResult(
                initiative_id=init.initiative_id,
                dispatched=False,
                reason="already_sent",
            )

        # --- Guard 2: dispatch lock (concurrent workers) ---
        if not self._scheduler.acquire_dispatch_lock(init.initiative_id):
            return DispatchResult(
                initiative_id=init.initiative_id,
                dispatched=False,
                reason="locked_by_another_worker",
            )

        try:
            # --- Delegate to the actual dispatch callback ---
            result = self._on_dispatch(init)

            if result.dispatched:
                self._scheduler.mark_sent(init)

            return result

        finally:
            self._scheduler.release_dispatch_lock(init.initiative_id)

    @staticmethod
    def _default_dispatch(init: PendingInitiative) -> DispatchResult:
        """Default no-op dispatcher (for testing)."""
        return DispatchResult(
            initiative_id=init.initiative_id,
            dispatched=True,
            reason="dispatched (no-op)",
            message=init.generated_message,
        )


# ------------------------------------------------------------------
# Factory helper
# ------------------------------------------------------------------


def create_initiative(
    user_id: UUID,
    character_id: str,
    initiative_type: str,
    generated_message: str,
    scheduled_at: datetime | None = None,
    apply_jitter: bool = True,
    context: Dict[str, Any] | None = None,
) -> PendingInitiative:
    """Factory for building a PendingInitiative ready for scheduling.

    If *scheduled_at* is None, defaults to "now".
    *apply_jitter* controls whether scheduled_with_jitter gets a ±5 min offset.
    """
    now = datetime.now(timezone.utc)
    base = scheduled_at or now
    jittered = _add_jitter(base) if apply_jitter else base

    return PendingInitiative(
        initiative_id=str(uuid4()),
        user_id=user_id,
        character_id=character_id,
        initiative_type=initiative_type,
        generated_message=generated_message,
        scheduled_at=base,
        scheduled_with_jitter=jittered,
        context=context or {},
        created_at=now,
    )
