#!/usr/bin/env bash
# scripts/deploy-prod.sh — 场景 2：香港服务器生产部署
#
# 用途：在香港（或任意海外）Linux 服务器上一次性部署 Heart/yuoyuo 生产环境
#
# 架构：
#   [用户浏览器 / 手机] → [Cloudflare 灰云 (可选)]
#     → [服务器 :443] → Caddy (自动 HTTPS via Let's Encrypt)
#       ├─ /api/* → api 容器（uvicorn）
#       ├─ /api/chat/ws → api 容器（WebSocket）
#       └─ / → 静态文件（web/dist）
#     后台：encoder-worker 容器（HEART_WORKERS_ENABLED=true）
#     数据：postgres 容器 + redis 容器
#
# 用法：
#   bash scripts/deploy-prod.sh                完整部署（首次或更新）
#   bash scripts/deploy-prod.sh --update       仅拉代码 + 重建镜像 + 重启（保留 DB）
#   bash scripts/deploy-prod.sh --migrate      仅跑数据库迁移
#   bash scripts/deploy-prod.sh --status       查看服务健康
#   bash scripts/deploy-prod.sh --logs [name]  查看日志（api/encoder-worker/caddy/all）
#   bash scripts/deploy-prod.sh --stop         停止所有服务
#   bash scripts/deploy-prod.sh --restart      重启所有服务
#
# 前置条件：
#   - Linux 服务器（Ubuntu 22.04+ 推荐；Debian 12+ 也可）
#   - 已安装 Docker + docker compose plugin
#   - 域名 A 记录已指向服务器 IP（yuoyuo.app + www.yuoyuo.app）
#   - 服务器 80 + 443 端口对公网开放
#   - 已 sudo 或 root（首次部署需要）

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_PROD="$REPO_ROOT/.env.prod"
COMPOSE_FILE="$REPO_ROOT/docker-compose.prod.yml"

c_green="\033[32m"; c_blue="\033[34m"; c_yellow="\033[33m"; c_red="\033[31m"; c_reset="\033[0m"
log()  { printf "${c_green}[prod]${c_reset} %s\n" "$*"; }
info() { printf "${c_blue}[info]${c_reset} %s\n" "$*"; }
warn() { printf "${c_yellow}[warn]${c_reset} %s\n" "$*"; }
die()  { printf "${c_red}[error]${c_reset} %s\n" "$*" >&2; exit 1; }

MODE="${1:-full}"

# ──────────────────────────────────────────────────────────────────────────────
# 前置检查
# ──────────────────────────────────────────────────────────────────────────────
check_prereqs() {
    command -v docker &>/dev/null || die "docker 未安装。参考 https://docs.docker.com/engine/install/ubuntu/"
    docker compose version &>/dev/null || die "docker compose plugin 未安装。运行: sudo apt install -y docker-compose-plugin"
    [[ -f "$COMPOSE_FILE" ]] || die "$COMPOSE_FILE 不存在，拉代码是否成功？"
    [[ -f "$REPO_ROOT/Caddyfile" ]] || die "$REPO_ROOT/Caddyfile 不存在"

    if ! docker ps &>/dev/null; then
        die "无权访问 docker。请将当前用户加入 docker 组：sudo usermod -aG docker \$USER 然后重登。"
    fi
}

DC() {
    docker compose -f "$COMPOSE_FILE" --env-file "$ENV_PROD" "$@"
}

# ──────────────────────────────────────────────────────────────────────────────
# --stop / --restart / --status / --logs
# ──────────────────────────────────────────────────────────────────────────────
case "$MODE" in
    --stop)
        check_prereqs
        log "停止所有生产服务..."
        DC down
        log "✅ 服务已停止（数据卷保留）"
        exit 0
        ;;
    --restart)
        check_prereqs
        log "重启所有生产服务..."
        DC restart
        log "✅ 服务已重启"
        DC ps
        exit 0
        ;;
    --status)
        check_prereqs
        log "生产服务状态："
        DC ps
        echo ""
        info "健康检查："
        curl -sf http://localhost:8000/health/live 2>/dev/null && echo " ✓ API live" || warn " ✗ API 不可达（可能未启动）"
        exit 0
        ;;
    --logs)
        check_prereqs
        target="${2:-all}"
        if [[ "$target" == "all" ]]; then
            DC logs -f --tail=100
        else
            DC logs -f --tail=100 "$target"
        fi
        exit 0
        ;;
esac

# ──────────────────────────────────────────────────────────────────────────────
# 配置 .env.prod（首次交互填写）
# ──────────────────────────────────────────────────────────────────────────────
setup_env_prod() {
    if [[ -f "$ENV_PROD" ]]; then
        info "✓ .env.prod 已存在，跳过生成（如需重置：mv .env.prod .env.prod.bak）"
        return
    fi

    log "生成 .env.prod（从模板 + 自动生成随机密钥）..."
    cp "$REPO_ROOT/.env.prod.example" "$ENV_PROD"

    command -v openssl &>/dev/null || die "openssl 未找到，无法生成密钥"

    local pg_pw redis_pw otp_pepper jwt_key
    pg_pw=$(openssl rand -hex 32)
    redis_pw=$(openssl rand -hex 32)
    otp_pepper=$(openssl rand -hex 32)
    jwt_key=$(openssl rand -hex 32)

    sed -i "s|POSTGRES_PASSWORD=.*|POSTGRES_PASSWORD=$pg_pw|" "$ENV_PROD"
    sed -i "s|REDIS_PASSWORD=.*|REDIS_PASSWORD=$redis_pw|" "$ENV_PROD"
    sed -i "s|OTP_PEPPER=.*|OTP_PEPPER=$otp_pepper|" "$ENV_PROD"

    # 默认用 HS256（简单可靠）；RS256 需要手动生成 PEM 对
    sed -i "s|^JWT_ALGORITHM=.*|JWT_ALGORITHM=HS256|" "$ENV_PROD"
    # 保留原有 JWT_PRIVATE_KEY / JWT_PUBLIC_KEY 行但把 SECRET 新增到文件
    if ! grep -q "^JWT_SECRET_KEY=" "$ENV_PROD"; then
        echo "" >> "$ENV_PROD"
        echo "# Auto-generated by deploy-prod.sh" >> "$ENV_PROD"
        echo "JWT_SECRET_KEY=$jwt_key" >> "$ENV_PROD"
    else
        sed -i "s|^JWT_SECRET_KEY=.*|JWT_SECRET_KEY=$jwt_key|" "$ENV_PROD"
    fi

    # 生产默认 VOICE_PROVIDER=minimax（用户偏好），会覆盖 example 里的 mimo
    sed -i "s|^VOICE_PROVIDER=.*|VOICE_PROVIDER=minimax|" "$ENV_PROD"

    chmod 600 "$ENV_PROD"

    echo ""
    warn "════════════════════════════════════════════════════════════"
    warn "  .env.prod 已生成，随机密钥已填充。以下字段必须手动填写："
    warn "════════════════════════════════════════════════════════════"
    warn ""
    warn "  DEEPSEEK_API_KEY=sk-..."
    warn "  EMBEDDING_API_KEY=sk-..."
    warn "  MINIMAX_API_KEY=sk-api-..."
    warn "  MINIMAX_GROUP_ID=..."
    warn "  MINIMAX_RIN_CLONE_VOICE_ID=yuoyuo_rin_v1"
    warn "  MINIMAX_DOROTHY_VOICE_ID=yuoyuo_dorothy_v1"
    warn "  MIMO_API_KEY=tp-...      # 若开启 fallback"
    warn "  RESEND_API_KEY=re_...    # 邮件服务"
    warn "  # S3 (Cloudflare R2 推荐)"
    warn "  S3_ENDPOINT_URL=https://<account>.r2.cloudflarestorage.com"
    warn "  S3_ACCESS_KEY_ID=..."
    warn "  S3_SECRET_ACCESS_KEY=..."
    warn "  S3_BUCKET_NAME=yuoyuo-media-prod"
    warn "  S3_REGION=auto"
    warn "  S3_PUBLIC_BASE_URL=https://pub-xxxxx.r2.dev"
    warn "  CORS_ALLOWED_ORIGINS=https://yuoyuo.app,https://www.yuoyuo.app"
    echo ""
    read -r -p "$(printf "${c_yellow}[prod]${c_reset} 现在编辑 .env.prod (Ctrl+X 保存退出)... 按 Enter 打开编辑器 ")"
    ${EDITOR:-nano} "$ENV_PROD"

    # 编辑后校验必填字段
    for key in DEEPSEEK_API_KEY MINIMAX_API_KEY; do
        val=$(grep "^$key=" "$ENV_PROD" | cut -d= -f2-)
        if [[ -z "$val" || "$val" == *"<your"* ]]; then
            die "$key 未填写，中止部署。请编辑 $ENV_PROD 后重新运行。"
        fi
    done

    info "✓ .env.prod 配置完成（权限 600）"
}

# ──────────────────────────────────────────────────────────────────────────────
# 构建前端静态文件
# ──────────────────────────────────────────────────────────────────────────────
build_frontend() {
    if [[ ! -d "$REPO_ROOT/web" ]]; then
        warn "web/ 目录不存在，跳过前端构建"
        return
    fi

    log "构建前端静态文件（web/dist）..."

    # 如果服务器没装 Node，用 docker 跑构建（避免污染宿主）
    if ! command -v node &>/dev/null || [[ "$(node -e 'process.stdout.write(String(parseInt(process.versions.node)))' 2>/dev/null || echo 0)" -lt 18 ]]; then
        warn "本机无合适 Node（需 ≥ 18），用 docker node:20 构建..."
        docker run --rm \
            -v "$REPO_ROOT/web:/app" \
            -w /app \
            node:20-alpine \
            sh -c "npm ci --silent && npm run build"
    else
        cd "$REPO_ROOT/web"
        npm ci --silent
        npm run build
    fi

    [[ -d "$REPO_ROOT/web/dist" ]] || die "web/dist 构建失败"
    info "✓ 前端构建完成（$(du -sh "$REPO_ROOT/web/dist" | cut -f1)）"
}

# ──────────────────────────────────────────────────────────────────────────────
# 启动数据层容器
# ──────────────────────────────────────────────────────────────────────────────
start_data_layer() {
    log "启动 postgres + redis..."
    DC up -d postgres redis

    log "等待 postgres 就绪..."
    for i in $(seq 1 30); do
        if DC ps postgres 2>/dev/null | grep -q "healthy"; then
            info "✓ postgres 就绪 (${i}s)"
            return
        fi
        sleep 1
    done
    die "postgres 30s 内未就绪，检查 docker logs: bash scripts/deploy-prod.sh --logs postgres"
}

# ──────────────────────────────────────────────────────────────────────────────
# 构建并启动 api / encoder-worker / caddy
# ──────────────────────────────────────────────────────────────────────────────
start_app_layer() {
    log "构建后端镜像（首次可能需要 3-5 分钟）..."
    DC build api encoder-worker

    log "启动 api + encoder-worker + caddy..."
    DC up -d api encoder-worker caddy

    log "等待 api 健康..."
    for i in $(seq 1 60); do
        if DC exec -T api curl -sf http://localhost:8000/health/live &>/dev/null; then
            info "✓ api 健康 (${i}s)"
            break
        fi
        sleep 1
    done
}

# ──────────────────────────────────────────────────────────────────────────────
# 运行数据库迁移
# ──────────────────────────────────────────────────────────────────────────────
run_migrations() {
    log "运行数据库迁移（两个 Alembic head）..."
    DC exec -T api python -m alembic upgrade 022_identity_narrative_backfill
    DC exec -T api python -m alembic upgrade 033_chat_messages_is_proactive

    echo ""
    info "当前迁移状态："
    DC exec -T api python -m alembic current
    echo ""
    info "✓ 数据库迁移完成（应显示两行 (head)）"
}

# ──────────────────────────────────────────────────────────────────────────────
# 打印最终状态
# ──────────────────────────────────────────────────────────────────────────────
print_summary() {
    echo ""
    echo "═══════════════════════════════════════════════════════════════"
    log "✅ 生产环境部署完成"
    echo "═══════════════════════════════════════════════════════════════"
    echo ""
    DC ps
    echo ""
    info "关键 URL："
    echo "  健康检查:   curl https://yuoyuo.app/health/live"
    echo "  首页:       https://yuoyuo.app"
    echo ""
    info "常用命令："
    echo "  状态:       bash scripts/deploy-prod.sh --status"
    echo "  日志(全部): bash scripts/deploy-prod.sh --logs"
    echo "  日志(api):  bash scripts/deploy-prod.sh --logs api"
    echo "  重启:       bash scripts/deploy-prod.sh --restart"
    echo "  停止:       bash scripts/deploy-prod.sh --stop"
    echo "  更新代码:   bash scripts/deploy-prod.sh --update"
    echo ""
    warn "⚠️  首次访问 https://yuoyuo.app 时 Caddy 会申请 Let's Encrypt 证书（约 30-60s）"
    warn "⚠️  如果证书失败，检查："
    warn "   1. 域名 A 记录是否指向此服务器 IP"
    warn "   2. 服务器 80 + 443 端口是否对公网开放"
    warn "   3. Cloudflare 灰云是否关闭（首次签发时必须直连服务器）"
}

# ──────────────────────────────────────────────────────────────────────────────
# 主流程
# ──────────────────────────────────────────────────────────────────────────────
main() {
    echo ""
    log "Heart/yuoyuo — 香港服务器生产部署"
    echo "──────────────────────────────────────────────────────────"

    check_prereqs

    case "$MODE" in
        --update)
            log "增量更新模式（拉代码 + 重建 + 重启，保留数据）"
            cd "$REPO_ROOT"
            git pull
            build_frontend
            DC build api encoder-worker
            DC up -d
            run_migrations
            print_summary
            ;;
        --migrate)
            log "仅运行数据库迁移"
            run_migrations
            ;;
        full|"")
            setup_env_prod
            build_frontend
            start_data_layer
            start_app_layer
            run_migrations
            print_summary
            ;;
        *)
            die "未知参数: $MODE （运行 bash scripts/deploy-prod.sh 查看用法）"
            ;;
    esac
}

main
