apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: heart-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: heart-prometheus
