"""Proactive messages table for Inner Loop persistence.

Revision ID: 018_proactive_messages
Revises: 017_embed_dim_1024
Create Date: 2026-07-08

Persists proactive messages generated by the SS06 Inner Loop worker.

Before this table existed the worker's ritual dedup query
(``SELECT COUNT(*) FROM proactive_messages ...``) raised UndefinedTable,
which was silently swallowed — so ``ritual_morning`` greetings were emitted
on every tick (once per minute at HEART_INNER_LOOP_INTERVAL_S=60), piling up
~240/day instead of the intended max-once-per-day. Persisting every proactive
message here makes the dedup query and the daily quota actually enforceable,
and lets ``/api/proactive/pending`` survive restarts.

Table: proactive_messages (HASH partitioned by user_id × 32, mirrors chat_messages)
"""

from alembic import op

revision = "018_proactive_messages"
down_revision = "017_embed_dim_1024"
branch_labels = None
depends_on = None

NUM_PARTITIONS = 32


def upgrade() -> None:
    # Parent table (partitioned by user_id, like chat_messages)
    op.execute(
        """
    CREATE TABLE proactive_messages (
        id            UUID NOT NULL DEFAULT gen_random_uuid(),
        user_id       UUID NOT NULL,
        character_id  TEXT NOT NULL,
        content       TEXT NOT NULL,
        trigger_type  TEXT NOT NULL,
        created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        delivered     BOOLEAN NOT NULL DEFAULT FALSE,
        delivered_at  TIMESTAMPTZ,

        PRIMARY KEY (id, user_id)
    ) PARTITION BY HASH (user_id)
    """
    )

    # Create 32 partitions
    for i in range(NUM_PARTITIONS):
        op.execute(
            f"CREATE TABLE proactive_messages_p{i} "
            f"PARTITION OF proactive_messages "
            f"FOR VALUES WITH (MODULUS {NUM_PARTITIONS}, REMAINDER {i})"
        )

    # Pending lookup: newest-first per user×character, delivered filtered in query.
    op.execute(
        "CREATE INDEX ix_proactive_user_char_created "
        "ON proactive_messages (user_id, character_id, created_at DESC)"
    )
    # Ritual dedup / daily quota: (user, character, trigger_type, created_at).
    op.execute(
        "CREATE INDEX ix_proactive_dedup "
        "ON proactive_messages (user_id, character_id, trigger_type, created_at)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS proactive_messages CASCADE")
